server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/powerup_user
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
jwt:
  secret: ${KEYSECRET_SECURITY:eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb25oQG1haWwuY29tIiwibmFtZSI6IkpvaG4gRG9lIiwicm9sZSI6MSwiaWF0IjoxNTE2MjM5MDIyfQ.Ab1B2G1UENl1yzzHkU4R0PkzsK0BM1By0sb8JbpK__LApPF4ybgA8siRIHjIMj23ymIyhfWKLtF3BQkuM5xdNg}
  expiration: ${EXPIRE_DAYS_SECURITY:3600000}

management:
  endpoints:
    web:
      exposure:
        include: "*"